apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boxes
namePrefix: jlewi-
labels:
- includeSelectors: true
  pairs:
    app: jlewi-box
resources:
- statefulset.yaml
- pvc.yaml
- sa.yaml
images:
- digest: sha256:f32338a3cf788da1fcac045efd662895f920fb96cf8fc6a3e43c4418cf6e7b49
  name: tensorflow
  newName: gcr.io/dev-bytetoko/devbox
