apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boxes
namePrefix: jlewi-
labels:
- includeSelectors: true
  pairs:
    app: jlewi-box
resources:
- statefulset.yaml
- pvc.yaml
- sa.yaml
images:
- digest: sha256:93787e30990a8f065e4f3e02edd0f461f759b47c30c80e09fb131ef9f985418a
  name: tensorflow
  newName: gcr.io/dev-bytetoko/devbox:200b871-dirty
