apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boxes
namePrefix: jlewi-
labels:
- includeSelectors: true
  pairs:
    app: jlewi-box
#- application.yaml
#- deployment.yaml
resources:
- statefulset.yaml
images:
- name: tensorflow
  newName: gcr.io/deeplearning-platform-release/tf-cpu.2-9
