apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: box
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # We need more storage.
      storage: 100Gi
  storageClassName: standard
  volumeMode: Filesystem
