# Setup the kaniko namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  #annotations:
  #  iam.gke.io/gcp-service-account: dev@dev-bytetoko.iam.gserviceaccount.com
  name: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "dev"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io