apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boxes
labels:
- includeSelectors: true
  pairs:
    app: basecpu
resources:
- statefulset.yaml
images:
- digest: sha256:4ac4eb33fcf0dd14dadda226d05b42fd825a0d707d0ad9028763c0624722fea8
  name: base-cpu
  newName: gcr.io/dev-bytetoko/google-deep-learning/base-cpu:3fa9629-dirty
