apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boxes
labels:
- includeSelectors: true
  pairs:
    app: basecpu
resources:
- statefulset.yaml
images:
- digest: sha256:2956e095a09b22d358f78e34d7b807469e115d68733fb7539580a0318a8c6971
  name: base-cpu
  newName: gcr.io/dev-bytetoko/google-deep-learning/base-cpu:70bae58-dirty
