apiVersion: v1
kind: Service
metadata:
  name: basecpu
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: pod
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: basecpu
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  # N.B. This is an attempt to ensure that when we update the statefulset we will kick the pod
  # even if there is only one pod.
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: box
  template:
    metadata:
      labels:    
        component: pod
    spec:
      containers:
      - image: base-cpu
        name: box
        # Explicitly set the command so we can use off the shelf notebook images.
        command:        
         - tail
         - -f
         - /dev/null
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
            ephemeral-storage:  10Gi
          requests:
            cpu: "4"
            memory: 4Gi
            ephemeral-storage:  10Gi
      serviceAccountName: jlewi-dev
