apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: vscode
  labels:
    somelabel: app
build:
  artifacts:
  - image: gcr.io/dev-bytetoko/quickstart-image
    context: .
    kaniko:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: dev-bytetoko
    machineType: E2_HIGHCPU_8
manifests:
  kustomize:
    paths:
    - .
  # cluster:
  #   namespace: kaniko
  #   serviceAccount: kaniko
  #   resources:
  #     requests:
  #       cpu: 4
  #       memory: 8Gi
  #       ephemeralStorage: 30Gi
  #     limits:
  #       cpu: 4
  #       memory: 8Gi
  #       ephemeralStorage: 30Gi

